dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT'
}

group 'com.willfp'
version rootProject.version

build.dependsOn publishToMavenLocal

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            artifactId 'ecomponent'
        }
    }
    repositories {
        maven {
            name = "Auxilor"
            url = uri("https://repo.auxilor.io/repository/maven-releases/")
            credentials {
                username = System.getenv("MAVEN_USERNAME")
                password = System.getenv("MAVEN_PASSWORD")
            }
        }
    }
}
